module.exports.regions = [
  {
    uid: 'region1',
    name: 'Region 1',
    description: 'Region 1: Central Europe',
    ranked: true,
    selectable: true,
  },
  {
    uid: 'region2',
    name: 'Region 2',
    description: 'Region 2: Africa',
    ranked: true,
    selectable: true,
  },
  {
    uid: 'region3',
    name: 'Region 3',
    description: 'Region 3: North America',
    ranked: true,
    selectable: true,
  },
  {
    uid: 'region4',
    name: 'Region 4',
    description: 'Region 4: South America',
    ranked: true,
    selectable: true,
  },
  {
    uid: 'region5',
    name: 'Region 5',
    description: 'Region 5: West Asia',
    ranked: true,
    selectable: true,
  },
  {
    uid: 'region6',
    name: 'Region 6',
    description: 'Region 6: East Asia',
    ranked: true,
    selectable: true,
  },
  {
    uid: 'region7',
    name: 'Region 7',
    description: 'Region 7: Oceania',
    ranked: true,
    selectable: true,
  },
  {
    uid: 'regionFree',
    name: 'No region lock',
    description: 'Worldwide',
    ranked: true,
    selectable: false,
  },
];
