module.exports.itemPools = [
  [
    'Crash Cove',
    'Roo\'s Tubes',
    'Coco Park',
    'Tiger Temple',
    'Dingo Canyon',
    'Blizzard Bluff',
    'Dragon Mines',
    'Inferno Island',
    'Jungle Boogie',
    'Meteor Gorge',
    'Koala Carnival',
  ],
  [
    'Mystery Caves',
    'Sewer Speedway',
    'Papu\'s Pyramid',
    'Tiny Arena',
    'N. Gin Labs',
    'Slide Coliseum',
    'Turbo Track',
    'Android Alley',
    'Barin Ruins',
    'Assembly Lane',
    'Electron Avenue',
  ],
  [
    'Polar Pass',
    'Cortex Castle',
    'Hot Air Skyway',
    'Clockwork Wumpa',
    'Prehistoric Playground',
    'Nina\'s Nightmare',
    'Gingerbread Joyride',
    'Megamix Mania',
  ],
  [
    'Oxide Station',
    'Tiny Temple',
    'Deep Sea Driving',
    'Thunder Struck',
    'Out of Time',
    'Twilight Tour',
    'Drive-Thru Danger',
  ],
];

module.exports.battlePools = [
  [
    'Skull Rock',
    'Rocky Road',
    'Rampage Ruins',
    'Temple Turmoil',
  ],
  [
    'Nitro Court',
    'Lab Basement',
    'Frozen Frenzy',
    'Magnetic Mayhem',
  ],
  [
    'Parking Lot',
    'The North Bowl',
    'Desert Storm',
    'Terra Drome',
  ],
];

module.exports._4v4Pools = [
  [
    'Crash Cove',
    'Roo\'s Tubes',
    'Coco Park',
    'Blizzard Bluff',
    'Inferno Island',
    'Jungle Boogie',
    'Meteor Gorge',
    'Koala Carnival',
  ],
  [
    'Tiger Temple',
    'Papu\'s Pyramid',
    'Dingo Canyon',
    'Dragon Mines',
    'Turbo Track',
    'Slide Coliseum',
    'Barin Ruins',
  ],
  [
    'Mystery Caves',
    'Sewer Speedway',
    'Tiny Arena',
    'N. Gin Labs',
    'Android Alley',
    'Assembly Lane',
    'Electron Avenue',
    'Spyro Circuit',
  ],
  [
    'Polar Pass',
    'Cortex Castle',
    'Hot Air Skyway',
    'Clockwork Wumpa',
    'Prehistoric Playground',
    'Nina\'s Nightmare',
    'Gingerbread Joyride',
    'Megamix Mania',
  ],
  [
    'Oxide Station',
    'Tiny Temple',
    'Deep Sea Driving',
    'Thunder Struck',
    'Out of Time',
    'Twilight Tour',
    'Drive-Thru Danger',
  ],
];

module.exports.spicyPools = [
  [
    'Crash Cove',
    'Roo\'s Tubes',
    'Coco Park',
    'Dingo Canyon',
    'Blizzard Bluff',
    'Dragon Mines',
    'Inferno Island',
    'Jungle Boogie',
    'Meteor Gorge',
    'Koala Carnival',
  ],
  [
    'Polar Pass',
    'Cortex Castle',
    'Hot Air Skyway',
    'Clockwork Wumpa',
    'Prehistoric Playground',
    'Nina\'s Nightmare',
    'Gingerbread Joyride',
    'Megamix Mania',
    'Oxide Station',
    'Tiny Temple',
    'Deep Sea Driving',
    'Thunder Struck',
    'Out of Time',
    'Twilight Tour',
    'Drive-Thru Danger',
  ],
  [
    'Electron Avenue',
    'Tiny Arena',
    'Oxide Station',
    'Android Alley',
    'Prehistoric Playground',
    'Assembly Lane',
    'Twilight Tour',
    'N. Gin Labs',
    // 'Spyro Circuit',
    'Hot Air Skyway',
    'Polar Pass',
  ],
  [
    'Mystery Caves',
    'Sewer Speedway',
    'Tiger Temple',
    'Papu\'s Pyramid',
    'Dragon Mines',
    'Tiny Arena',
    'Slide Coliseum',
    'Android Alley',
    'Assembly Lane',
    'Barin Ruins',
    // 'Spyro Circuit',
  ],
];
