module.exports = [
  [
    'Crash Cove',
    'Roo\'s Tubes',
    'Coco Park',
    'Tiger Temple',
    'Dingo Canyon',
    'Blizzard Bluff',
    'Dragon Mines',
    'Inferno Island',
    'Jungle Boogie',
    'Meteor Gorge',
    'Koala Carnival',
  ],
  [
    'Mystery Caves',
    'Sewer Speedway',
    'Papu\'s Pyramid',
    'Tiny Arena',
    'N. Gin Labs',
    'Slide Coliseum',
    'Turbo Track',
    'Android Alley',
    'Barin Ruins',
    'Assembly Lane',
    'Electron Avenue',
    'Spyro Circuit',
  ],
  [
    'Polar Pass',
    'Cortex Castle',
    'Hot Air Skyway',
    'Oxide Station',
    'Clockwork Wumpa',
    'Tiny Temple',
    'Deep Sea Driving',
    'Thunder Struck',
    'Out of Time',
    'Twilight Tour',
    'Prehistoric Playground',
    'Nina\'s Nightmare',
    'Gingerbread Joyride',
    'Megamix Mania',
    'Drive-Thru Danger',
  ],
];
